const App = { page:'close', selectedOrder:null, draftUnit:'pack', draftQty:1, draftBoxMode:'parcel' };
const LS = 'khokai_partner_pos_v214';
const CFG = 'khokai_partner_cfg_v214';
const fmt = n => '₩ ' + Number(n||0).toLocaleString('ko-KR');
const today = () => new Date().toISOString().slice(0,10);
const nowLocal = () => { const d=new Date(); const z=n=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`; };
const uid = p => p + '-' + Math.random().toString(36).slice(2,8);
const seed = {
  tiers:[{id:'retail',name:'Retail'},{id:'restaurant',name:'Restaurant'},{id:'mart',name:'Mart'},{id:'wholesale',name:'Wholesale'},{id:'vip',name:'VIP'}],
  partners:[
    {id:'pt1',name:'아이비',tier:'restaurant',phone:'010-7633-2000',address:'경기도 안산시 단원구 다문화1길 68, 1층',credit_days:7,balance:8550000,biz_no:'684-86-02697'},
    {id:'pt2',name:'Thai Mart Seoul',tier:'mart',phone:'010-1111-2222',address:'서울',credit_days:3,balance:0,biz_no:''}
  ],
  products:[
    {id:'pork1',sku:'KH-PORK-1KG',option_id:'PO-KH-PORK-1KG',display_product_id:'DP-KH-PORK',name_th:'ลูกชิ้นหมูพรีเมียม 1kg',name_ko:'돼지볼 커카이 1kg',parcel_box_qty:15,truck_box_qty:20,prices:{retail:14900,restaurant:13500,mart:13200,wholesale:12800,vip:12500}},
    {id:'mix1',sku:'KH-MIX-1KG',option_id:'PO-KH-MIX-1KG',display_product_id:'DP-KH-MIX',name_th:'ลูกชิ้นหมู+ไก่ 1kg',name_ko:'미트볼 커카이 2호 1kg',parcel_box_qty:15,truck_box_qty:20,prices:{retail:12000,restaurant:10800,mart:10500,wholesale:10200,vip:10000}},
    {id:'cart1',sku:'KH-CART-1KG',option_id:'PO-KH-CART-1KG',display_product_id:'DP-KH-CART',name_th:'ลูกชิ้นเอ็นไก่ 1kg',name_ko:'미트볼 커카이 3호 1kg',parcel_box_qty:15,truck_box_qty:20,prices:{retail:12000,restaurant:10800,mart:10500,wholesale:10200,vip:10000}},
    {id:'muyo700',sku:'KH-MUYO-700G',option_id:'PO-KH-MUYO-700G',display_product_id:'DP-KH-MUYO',name_th:'หมูยอ 700g',name_ko:'여우본 700g',parcel_box_qty:20,truck_box_qty:24,prices:{retail:10000,restaurant:9000,mart:8700,wholesale:8500,vip:8200}}
  ],
  orders:[]
};
let db = load();
function load(){ try{ return JSON.parse(localStorage.getItem(LS)) || structuredClone(seed); }catch(e){ return JSON.parse(JSON.stringify(seed)); } }
function save(){ localStorage.setItem(LS, JSON.stringify(db)); }
function cfg(){ try{return JSON.parse(localStorage.getItem(CFG))||{tracking_base:''}}catch(e){return{tracking_base:''}} }
function saveCfg(c){ localStorage.setItem(CFG, JSON.stringify(c)); }
const partner = id => db.partners.find(x=>x.id===id);
const product = id => db.products.find(x=>x.id===id);
const defaultTier = o => partner(o.partner_id)?.tier || 'restaurant';
const priceOf = (pr,tier) => Number(pr?.prices?.[tier] || pr?.prices?.restaurant || pr?.prices?.retail || 0);
const boxQty = (pr,mode) => Number(mode==='truck' ? (pr.truck_box_qty||pr.parcel_box_qty||1) : (pr.parcel_box_qty||pr.truck_box_qty||1));
function calc(o){ o.total = o.items.reduce((a,it)=>a+Number(it.line_total||0),0); }
function safeOrder(){ let o=db.orders.find(x=>x.status==='draft'); if(!o){ o={id:uid('ord'),no:'B2B-'+Date.now().toString().slice(-8),date:today(),status:'draft',payment_status:'pending',partner_id:'',delivery_date:'',delivery_method:'parcel',items:[],total:0}; db.orders.unshift(o); save(); } return o; }
function nav(){ return [['close','ปิด'],['ship','รวม/OMS'],['orders','Order'],['partners','Partner'],['products','Product'],['settings','ตั้งค่า']].map(([p,t])=>`<button class="${App.page===p?'active':''}" onclick="go('${p}')">${t}</button>`).join(''); }
function header(){ return `<div class="top"><div class="top-inner compact-head"><div><div class="brand small-brand">KHOKAI ERP Lite</div><div class="tag small-tag">V2.1.4</div></div></div><div class="nav no-print">${nav()}</div></div>`; }
function bottom(){ return `<div class="bottom-bar no-print">${nav()}</div>`; }
function go(p){ App.page=p; App.selectedOrder=null; render(); }
function render(){ document.body.innerHTML = header()+`<main class="app">${pages[App.page]()}</main>`+bottom(); }
const pages = {close, ship, orders, partners, products, settings};
function productLabel(pr){ return `${pr.name_th||pr.name_ko||pr.sku} / ${pr.name_ko||''}`; }
function productOptions(){ return db.products.map(p=>`<option value="${p.id}">${productLabel(p)}</option>`).join(''); }
function unitButtons(){ return `<div class="seg"><button type="button" class="${App.draftUnit==='pack'?'on':''}" onclick="setUnit('pack')">แพ็ก/ชิ้น</button><button type="button" class="${App.draftUnit==='box'?'on':''}" onclick="setUnit('box')">ลัง</button></div>`; }
function boxModeButtons(){ return `<div class="seg small-seg"><button type="button" class="${App.draftBoxMode==='parcel'?'on':''}" onclick="setBoxMode('parcel')">พัสดุ</button><button type="button" class="${App.draftBoxMode==='truck'?'on':''}" onclick="setBoxMode('truck')">รถส่ง</button></div>`; }
function qtyControl(){ return `<div class="qtybox"><div class="row qty-row"><button type="button" class="qtybtn" onclick="setQty(App.draftQty-1)">−</button><input class="input qty-input" id="qty" type="number" min="1" value="${App.draftQty}" onchange="setQty(this.value)"><button type="button" class="qtybtn" onclick="setQty(App.draftQty+1)">+</button></div><div class="quick-qty">${[1,2,3,5,10].map(n=>`<button type="button" class="${App.draftQty===n?'on':''}" onclick="setQty(${n})">${n}</button>`).join('')}</div></div>`; }
function addProductBlock(oid, compact=false){ return `<div class="addbox ${compact?'compact-add':''}"><div class="form-grid one-mobile v214-grid"><div><label>สินค้า</label><select id="pselect">${productOptions()}</select></div><div><label>หน่วย</label>${unitButtons()}</div><div id="boxModeWrap" style="display:${App.draftUnit==='box'?'block':'none'}"><label>จำนวนต่อลัง</label>${boxModeButtons()}</div><div><label>จำนวน</label>${qtyControl()}</div><div class="end"><button class="small-action" onclick="addItem('${oid}')">+ เพิ่มสินค้า</button></div></div></div>`; }
function setUnit(v){ App.draftUnit=v; render(); }
function setBoxMode(v){ App.draftBoxMode=v; render(); }
function setQty(v){ App.draftQty=Math.max(1, Number(v||1)); render(); }
function addItem(oid){ const o=db.orders.find(x=>x.id===oid); const pr=product(document.getElementById('pselect').value); const sell_unit=App.draftUnit || 'pack'; const mode=App.draftBoxMode || o.delivery_method || 'parcel'; const qty=Number(App.draftQty||1); const pack_qty=sell_unit==='box' ? qty*boxQty(pr,mode) : qty; const unit_price=priceOf(pr, defaultTier(o)); o.items.push({product_id:pr.id,sell_unit,box_mode:mode,box_qty_used:sell_unit==='box'?boxQty(pr,mode):1,qty,pack_qty,unit_price,line_total:pack_qty*unit_price}); calc(o); App.draftQty=1; save(); render(); }
function removeItem(oid,i){ const o=db.orders.find(x=>x.id===oid); o.items.splice(i,1); calc(o); save(); render(); }
function itemsHtml(o, editable=true){ if(!o.items.length) return '<div class="sub center-pad">ยังไม่มีสินค้า</div>'; return `<div class="list compact-list">${o.items.map((it,i)=>{const pr=product(it.product_id)||{};return `<div class="list-item compact-item"><div style="flex:1"><b>${pr.name_th||pr.name_ko||''}</b><div class="sub">${it.sell_unit==='box'?'ลัง':'แพ็ก'} x ${it.qty} · จริง ${it.pack_qty} แพ็ก${it.sell_unit==='box'?` · ${it.box_qty_used}/ลัง`:''}</div></div><b>${fmt(it.line_total)}</b>${editable?`<button class="btn-danger tiny" onclick="removeItem('${o.id}',${i})">ลบ</button>`:''}</div>`}).join('')}</div>`; }
function close(){ const o=safeOrder(); return `<div class="title slim-title">ปิดออเดอร์ด่วน</div><div class="sub">เลือกสินค้าให้จบก่อน ลูกค้าโอนแล้วค่อยมากรอก Partner / วันส่ง / วิธีส่ง / ข้อมูลโอน</div><div class="card clean-card">${addProductBlock(o.id,true)}<div style="margin-top:10px">${itemsHtml(o,true)}</div><div class="row total-row"><div class="num money">${fmt(o.total)}</div><div class="spacer"></div><button class="btn3 tiny" onclick="copyText(closeMsg(o,'th'))">ก๊อปไทย</button><button class="btn3 tiny" onclick="copyText(closeMsg(o,'ko'))">Copy KO</button><button class="tiny" onclick="App.selectedOrder='${o.id}';App.page='orders';render()">ไปกรอกหลังโอน</button></div></div><div class="card clean-card"><div class="title small-title">ข้อความปิดการขาย</div><div class="msggrid"><textarea readonly>${closeMsg(o,'th')}</textarea><textarea readonly>${closeMsg(o,'ko')}</textarea></div></div>`; }
function closeMsg(o,lang){ const lines=o.items.map(it=>{const pr=product(it.product_id)||{};const name=lang==='ko'?(pr.name_ko||pr.name_th):(pr.name_th||pr.name_ko); const unit=lang==='ko'?(it.sell_unit==='box'?'박스':'팩'):(it.sell_unit==='box'?'ลัง':'แพ็ก'); return `- ${name} x ${it.qty} ${unit}`;}).join('\n'); const track=trackingLink(o); if(lang==='ko') return [`주문 확인드립니다.`,``,lines||'- 상품 선택 전',``, `합계: ${fmt(o.total)}`,`입금계좌: 신한 140-013-678642 메콩푸드(주)`,`배송예정일: 입금 확인 후 안내`,`주문상태 확인: ${track}`,`감사합니다.`].join('\n'); return [`สรุปออเดอร์ครับ`, ``, lines||'- ยังไม่ได้เลือกสินค้า', ``, `ยอดรวม: ${fmt(o.total)}`, `บัญชีโอน: 신한 140-013-678642 메콩푸드(주)`, `วันจัดส่ง: แจ้งหลังยืนยันโอน`, `ลิงก์ติดตามสถานะ: ${track}`, `ขอบคุณครับ 🙏`].join('\n'); }
function trackingLink(o){ const base=(cfg().tracking_base||'').replace(/\/$/,''); return base ? `${base}/t/${o.no}` : `ตั้งค่า Tracking URL ก่อน/t/${o.no}`; }
function copyText(t){ navigator.clipboard?.writeText(t); alert('คัดลอกแล้ว'); }
function orders(){ if(App.selectedOrder) return orderDetail(App.selectedOrder); return `<div class="title">Order</div><div class="list">${db.orders.map(o=>`<div class="list-item"><div style="flex:1"><b>${o.no}</b><div class="sub">${o.status} · ${partner(o.partner_id)?.name||'ยังไม่เลือก Partner'} · ${fmt(o.total)}</div></div><button onclick="App.selectedOrder='${o.id}';render()">เปิด</button></div>`).join('')}</div>`; }
function partnerOptions(id){ return `<option value="">ยังไม่เลือก Partner</option>`+db.partners.map(p=>`<option value="${p.id}" ${id===p.id?'selected':''}>${p.name} (${p.tier})</option>`).join(''); }
function orderDetail(id){ const o=db.orders.find(x=>x.id===id); return `<button class="btn3 tiny" onclick="App.selectedOrder=null;render()">← กลับ</button><div class="card clean-card"><div class="title">${o.no}</div><div class="form-grid"><div><label>Partner หลังโอน</label><select onchange="o.partner_id=this.value;reprice(o);save();render()">${partnerOptions(o.partner_id)}</select></div><div><label>วันจัดส่ง หลังโอน</label><input class="input" type="date" value="${o.delivery_date||''}" onchange="o.delivery_date=this.value;save();render()"></div><div><label>ช่องทางส่ง หลังโอน</label><select onchange="o.delivery_method=this.value;rebox(o);save();render()"><option value="parcel" ${o.delivery_method!=='truck'?'selected':''}>พัสดุ / 택배</option><option value="truck" ${o.delivery_method==='truck'?'selected':''}>รถส่งถึงที่ / 직접배송</option></select></div><div><label>สถานะเงิน</label><select onchange="o.payment_status=this.value;save();render()"><option value="pending" ${o.payment_status==='pending'?'selected':''}>รอโอน</option><option value="paid" ${o.payment_status==='paid'?'selected':''}>โอนแล้ว</option><option value="unpaid" ${o.payment_status==='unpaid'?'selected':''}>เครดิต/ยังไม่จ่าย</option></select></div><div><label>ชื่อผู้โอน</label><input class="input" value="${o.payment_name||''}" onchange="o.payment_name=this.value;save()"></div><div><label>วัน-เวลาที่โอน</label><input class="input" type="datetime-local" value="${o.payment_datetime||''}" onchange="o.payment_datetime=this.value;save()"></div><div><label>ยอดโอน</label><input class="input" type="number" value="${o.payment_amount||''}" onchange="o.payment_amount=Number(this.value||0);save()"></div></div></div><div class="card clean-card" style="margin-top:10px"><div class="title small-title">เพิ่ม/แก้สินค้า</div>${addProductBlock(o.id)}${itemsHtml(o,true)}<h2 class="money">รวม ${fmt(o.total)}</h2></div><div class="card clean-card" style="margin-top:10px"><div class="row mobile-stack"><button class="btn3 tiny" onclick="copyText(closeMsg(db.orders.find(x=>x.id==='${id}'),'th'))">ก๊อปปิดขาย ไทย</button><button class="btn3 tiny" onclick="copyText(closeMsg(db.orders.find(x=>x.id==='${id}'),'ko'))">Copy closing KO</button><button class="tiny" onclick="exportOMS('${id}')">Export OMS</button><button class="btn3 tiny" onclick="printTrade('${id}')">거래명세서</button></div></div>`; }
function reprice(o){ o.items.forEach(it=>{const pr=product(it.product_id); it.unit_price=priceOf(pr,defaultTier(o)); it.line_total=it.unit_price*it.pack_qty;}); calc(o); }
function rebox(o){ o.items.forEach(it=>{ if(it.sell_unit==='box'){const pr=product(it.product_id); it.box_mode=o.delivery_method||'parcel'; it.box_qty_used=boxQty(pr,it.box_mode); it.pack_qty=it.qty*it.box_qty_used; it.line_total=it.unit_price*it.pack_qty; }}); calc(o); }
function ship(){ const d=today(); const os=db.orders.filter(o=>o.date===d||o.delivery_date===d); const sum={}; os.forEach(o=>o.items.forEach(it=>{const pr=product(it.product_id)||{}; const k=pr.id; if(!sum[k])sum[k]={name:pr.name_th||pr.name_ko,pack:0,total:0}; sum[k].pack+=it.pack_qty; sum[k].total+=it.line_total;})); return `<div class="title">รวมยอด / OMS</div><div class="card clean-card"><div class="sub">วันนี้ ${d}</div>${Object.values(sum).map(x=>`<div class="list-item"><div style="flex:1"><b>${x.name}</b><div class="sub">${x.pack} แพ็ก</div></div><b>${fmt(x.total)}</b></div>`).join('')||'<div class="sub">ยังไม่มีออเดอร์วันนี้</div>'}<button class="tiny" onclick="exportOMSAll()">Export OMS ทั้งวัน</button></div>`; }
function partners(){ return `<div class="title">Partner</div><div class="list">${db.partners.map(p=>`<div class="list-item"><div><b>${p.name}</b><div class="sub">${p.tier} · ${p.phone}</div></div></div>`).join('')}</div>`; }
function products(){ return `<div class="title">Product Master</div><div class="card clean-card"><button class="tiny" onclick="syncProductOption()">Sync product_option</button><div class="list" style="margin-top:10px">${db.products.map(p=>`<div class="list-item"><div style="flex:1"><b>${p.name_th}</b><div class="sub">${p.name_ko} · SKU ${p.sku}<br>옵션ID ${p.option_id} · 노출상품ID ${p.display_product_id}<br>พัสดุ ${p.parcel_box_qty}/ลัง · รถ ${p.truck_box_qty}/ลัง</div></div></div>`).join('')}</div></div>`; }
function settings(){ const c=cfg(); return `<div class="title">ตั้งค่า</div><div class="card clean-card"><div class="form-grid"><div><label>Supabase URL</label><input class="input" id="supUrl" value="${c.url||''}"></div><div><label>Supabase anon key</label><input class="input" id="supKey" value="${c.key||''}"></div><div><label>Tracking base URL</label><input class="input" id="trackBase" value="${c.tracking_base||''}" placeholder="https://xxxx.netlify.app"></div><div class="end"><button onclick="saveSettings()">บันทึกตั้งค่า</button></div></div><div class="row" style="margin-top:10px"><button class="btn3 tiny" onclick="syncProductOption()">Sync product_option</button><button class="btn-danger tiny" onclick="localStorage.removeItem(LS);location.reload()">Reset ข้อมูลทดลอง</button></div></div>`; }
function saveSettings(){ saveCfg({url:document.getElementById('supUrl').value.trim(),key:document.getElementById('supKey').value.trim(),tracking_base:document.getElementById('trackBase').value.trim()}); alert('บันทึกแล้ว'); }
async function syncProductOption(){ const c=cfg(); if(!c.url||!c.key){ alert('ใส่ Supabase URL และ anon key ในตั้งค่าก่อน'); return; } const client=supabase.createClient(c.url,c.key); const {data,error}=await client.from('product_option').select('*').eq('active',true).limit(500); if(error){ alert('Sync ไม่ได้: '+error.message); return; } db.products=(data||[]).map(normProduct); save(); alert('Sync product_option แล้ว '+db.products.length+' รายการ'); render(); }
function normProduct(r){ const base=Number(r.pack_per_box||r.box_qty||r.packs_per_box||1)||1; const parcel=Number(r.parcel_box_qty||r.box_qty_parcel||base)||base; const truck=Number(r.truck_box_qty||r.box_qty_truck||base)||base; const retail=Number(r.tier_retail||r.retail_price||r.price||0)||0; const restaurant=Number(r.tier_restaurant||r.restaurant_price||r.partner_price||retail)||retail; const mart=Number(r.tier_mart||r.mart_price||restaurant)||restaurant; const wholesale=Number(r.tier_wholesale||r.wholesale_price||mart)||mart; const vip=Number(r.tier_vip||r.vip_price||wholesale)||wholesale; return {id:String(r.id||r.option_id||r.sku),sku:r.sku||r.product_sku||'',option_id:r.option_id||r.coupang_option_id||'',display_product_id:r.display_product_id||r.exposed_product_id||r.nochul_product_id||'',name_th:r.product_name_th||r.name_th||r.product_name||r.sku||'',name_ko:r.product_name_ko||r.name_ko||r.product_name_kr||r.product_name||r.sku||'',parcel_box_qty:parcel,truck_box_qty:truck,prices:{retail,restaurant,mart,wholesale,vip},raw:r}; }
function csvCell(v){ return '"'+String(v??'').replace(/"/g,'""')+'"'; }
function download(name,rows){ const csv=rows.map(r=>r.map(csvCell).join(',')).join('\n'); const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); }
function omsRows(os){ const rows=[['order_no','partner','delivery_date','sku','option_id','display_product_id','product_name','sell_unit','qty','pack_qty','unit_price','amount','delivery_method','tracking_url']]; os.forEach(o=>o.items.forEach(it=>{const pr=product(it.product_id)||{}; rows.push([o.no,partner(o.partner_id)?.name||'',o.delivery_date||'',pr.sku||'',pr.option_id||'',pr.display_product_id||'',pr.name_ko||pr.name_th,it.sell_unit,it.qty,it.pack_qty,it.unit_price,it.line_total,o.delivery_method||'parcel',trackingLink(o)]);})); return rows; }
function exportOMS(id){ const o=db.orders.find(x=>x.id===id); download(o.no+'_OMS.csv', omsRows([o])); }
function exportOMSAll(){ download('OMS_'+today()+'.csv', omsRows(db.orders.filter(o=>o.date===today()||o.delivery_date===today()))); }
function printTrade(id){ alert('거래명세서 print จะใส่ต่อ V2.1.4'); }
render();
