const App={page:'dashboard',selectedPartner:null,selectedOrder:null};
const fmt=n=>'₩ '+Number(n||0).toLocaleString('ko-KR');
const today=()=>new Date().toISOString().slice(0,10);
const daysBetween=d=>Math.floor((new Date(today())-new Date(d))/(1000*60*60*24));
const uid=p=>p+'-'+Math.random().toString(36).slice(2,8);
const LS='khokai_partner_pos_v2';
const seed={
 tiers:[{id:'retail',name:'Retail'},{id:'restaurant',name:'Restaurant'},{id:'mart',name:'Mart'},{id:'wholesale',name:'Wholesale'},{id:'vip',name:'VIP'}],
 products:[
  {id:'pork1',sku:'KH-PORK-1KG',name_th:'ลูกชิ้นหมูพรีเมียม',name_kr:'돼지볼 커카이 1kg',unit:'pack',box_unit:'box',box_qty:15,spec:'15kg/box',prices:{retail:14900,restaurant:13500,mart:13200,wholesale:12800,vip:12500},stock_pack:220},
  {id:'pork700',sku:'KH-PORK-700G',name_th:'ลูกชิ้นหมูพรีเมียม 700g',name_kr:'돼지볼 커카이 700g',unit:'pack',box_unit:'box',box_qty:20,spec:'14kg/box',prices:{retail:11200,restaurant:9800,mart:9500,wholesale:9200,vip:9000},stock_pack:180},
  {id:'mix1',sku:'KH-MIX-1KG',name_th:'ลูกชิ้นหมู+ไก่',name_kr:'미트볼 커카이 2호 1kg',unit:'pack',box_unit:'box',box_qty:15,spec:'15kg/box',prices:{retail:12000,restaurant:10800,mart:10500,wholesale:10200,vip:10000},stock_pack:140},
  {id:'cart1',sku:'KH-CART-1KG',name_th:'ลูกชิ้นเอ็นไก่',name_kr:'미트볼 커카이 3호 1kg',unit:'pack',box_unit:'box',box_qty:15,spec:'15kg/box',prices:{retail:12000,restaurant:10800,mart:10500,wholesale:10200,vip:10000},stock_pack:90},
  {id:'muyo700',sku:'KH-MUYO-700G',name_th:'หมูยอ',name_kr:'여우본 700g',unit:'pack',box_unit:'box',box_qty:20,spec:'14kg/box',prices:{retail:10000,restaurant:9000,mart:8700,wholesale:8500,vip:8200},stock_pack:75}
 ],
 partners:[
  {id:'pt1',name:'아이비',tier:'restaurant',phone:'010-7633-2000',address:'경기도 안산시 단원구 다문화1길 68, 1층',seller:'เก๋ง',credit_days:7,route_day:'Tue',payment_avg_days:2.4,balance:8550000,tax_type:'tax_invoice',biz_no:'684-86-02697'},
  {id:'pt2',name:'Thai Mart Seoul',tier:'mart',phone:'010-1111-2222',address:'서울',seller:'ทีมขาย',credit_days:3,route_day:'Wed',payment_avg_days:1.2,balance:0,tax_type:'cash_receipt',biz_no:''},
  {id:'pt3',name:'Wholesale Kim',tier:'wholesale',phone:'010-3333-4444',address:'인천',seller:'ทีมขาย',credit_days:14,route_day:'Fri',payment_avg_days:5.1,balance:1200000,tax_type:'tax_invoice',biz_no:'123-45-67890'}
 ],
 orders:[]
};
function load(){const raw=localStorage.getItem(LS);if(!raw){const s=structuredClone(seed);makeDemoOrders(s);localStorage.setItem(LS,JSON.stringify(s));return s}return JSON.parse(raw)}
function save(){localStorage.setItem(LS,JSON.stringify(db))}
function makeDemoOrders(s){const dates=['2026-06-12','2026-06-22','2026-07-02','2026-07-05','2026-05-17','2026-04-04'];let i=1;for(const d of dates){const p=s.partners[i%3];const prod=s.products[i%s.products.length];const qty=i%2?2:1;const pack=qty*(prod.box_qty||1);const unit=prod.prices[p.tier];s.orders.push({id:'ord'+i,no:'B2B-2607-'+String(i).padStart(4,'0'),date:d,partner_id:p.id,status:i%3?'delivered':'open',payment_status:i%2?'paid':'unpaid',due_date:new Date(new Date(d).getTime()+p.credit_days*86400000).toISOString().slice(0,10),paid_date:i%2?new Date(new Date(d).getTime()+Math.ceil(p.payment_avg_days)*86400000).toISOString().slice(0,10):'',items:[{product_id:prod.id,sell_unit:'box',qty,pack_qty:pack,unit_price:unit,line_total:pack*unit}],total:pack*unit}) ;i++}}
let db=load();
function partner(id){return db.partners.find(x=>x.id===id)}function product(id){return db.products.find(x=>x.id===id)}
function partnerStats(pid){const os=db.orders.filter(o=>o.partner_id===pid);const last=os.sort((a,b)=>b.date.localeCompare(a.date))[0];const oneYear=os.filter(o=>daysBetween(o.date)<=365);const paid=oneYear.filter(o=>o.payment_status==='paid');const total=oneYear.reduce((a,o)=>a+o.total,0);const paidTotal=paid.reduce((a,o)=>a+o.total,0);let gaps=[];const ds=oneYear.map(o=>o.date).sort();for(let i=1;i<ds.length;i++)gaps.push(Math.max(1,daysBetween(ds[i-1])-daysBetween(ds[i])));const avgGap=gaps.length?Math.round(gaps.reduce((a,b)=>a+b,0)/gaps.length):14;const since=last?daysBetween(last.date):999;const next=Math.max(0,avgGap-since);const bal=os.filter(o=>o.payment_status!=='paid').reduce((a,o)=>a+o.total,0)+Number(partner(pid)?.balance||0);const score=Math.max(20,Math.min(100,100-(bal?15:0)-Math.max(0,since-avgGap)*3));return{last,lastDays:since,orderCount:oneYear.length,total,paidTotal,avgOrder:oneYear.length?Math.round(total/oneYear.length):0,avgGap,next,bal,score}}
function top(){return `<div class="top"><div class="top-inner"><div><div class="brand">KHOKAI ERP Lite</div><div class="tag">Partner POS V2 · mobile first</div></div><div class="spacer"></div><button class="btn3 no-print" onclick="openSettings()">ตั้งค่า</button></div><div class="nav no-print">${navBtns()}</div></div>`}
function navBtns(){return [['dashboard','Dashboard'],['partners','Partner'],['products','Product'],['orders','Order'],['docs','Documents']].map(([p,t])=>`<button class="${App.page===p?'active':''}" onclick="go('${p}')">${t}</button>`).join('')}
function bottom(){return `<div class="bottom-bar no-print">${navBtns()}</div>`}
function go(p){App.page=p;App.selectedPartner=null;App.selectedOrder=null;render()}
function render(){document.body.innerHTML=top()+`<main class="app">${pages[App.page]()}</main>`+bottom()}
const pages={dashboard,partners,products,orders,docs};
function dashboard(){const totalToday=db.orders.filter(o=>o.date===today()).reduce((a,o)=>a+o.total,0);const month=today().slice(0,7);const totalMonth=db.orders.filter(o=>o.date.startsWith(month)).reduce((a,o)=>a+o.total,0);const ar=db.orders.filter(o=>o.payment_status!=='paid').reduce((a,o)=>a+o.total,0)+db.partners.reduce((a,p)=>a+(p.balance||0),0);const need=db.partners.map(p=>({p,s:partnerStats(p.id)})).filter(x=>x.s.next<=2||x.s.bal>0);return `<div class="title">Dashboard</div><div class="grid"><div class="card kpi"><div class="label">ยอดวันนี้</div><div class="num money">${fmt(totalToday)}</div></div><div class="card kpi"><div class="label">ยอดเดือนนี้</div><div class="num money">${fmt(totalMonth)}</div></div><div class="card kpi"><div class="label">ยอดค้าง</div><div class="num money">${fmt(ar)}</div></div><div class="card kpi"><div class="label">Partner</div><div class="num">${db.partners.length}</div></div></div><div class="card" style="margin-top:12px"><div class="title">ควรติดตามวันนี้</div><div class="list">${need.map(x=>`<div class="list-item"><div style="flex:1"><b>${x.p.name}</b><div class="sub">สั่งล่าสุด ${x.s.lastDays} วัน · ปกติทุก ${x.s.avgGap} วัน · ค้าง ${fmt(x.s.bal)}</div></div><span class="pill ${x.s.bal?'orange':'green'}">Score ${x.s.score}</span><button onclick="viewPartner('${x.p.id}')">เปิด</button></div>`).join('')||'<div class="sub">ยังไม่มีรายการต้องติดตาม</div>'}</div></div>`}
function partners(){if(App.selectedPartner)return partnerDetail(App.selectedPartner);return `<div class="row mobile-stack"><div class="title" style="flex:1">Partner Master</div><button onclick="newPartner()">+ Partner</button></div><div class="list">${db.partners.map(p=>{const s=partnerStats(p.id);return `<div class="list-item"><div style="flex:1"><b>${p.name}</b><div class="sub">${p.tier} · ${p.phone} · ส่ง ${p.route_day}</div><div class="sub">ล่าสุด ${s.lastDays} วัน · 1 ปี ${s.orderCount} ครั้ง · ${fmt(s.total)}</div></div><span class="pill ${s.score>80?'green':s.score>55?'orange':'red'}">${s.score}</span><button onclick="viewPartner('${p.id}')">ดู</button></div>`}).join('')}</div>`}
function viewPartner(id){App.page='partners';App.selectedPartner=id;render()}
function partnerDetail(id){const p=partner(id);const s=partnerStats(id);return `<button class="btn3 no-print" onclick="App.selectedPartner=null;render()">← กลับ</button><div class="card"><div class="row mobile-stack"><div style="flex:1"><div class="title">${p.name}</div><div class="sub">${p.tier} · ${p.phone}</div><div class="sub">${p.address}</div></div><span class="pill ${s.score>80?'green':s.score>55?'orange':'red'}">Partner Score ${s.score}</span></div></div><div class="grid" style="margin-top:12px"><div class="card kpi"><div class="label">สั่งล่าสุด</div><div class="num">${s.lastDays} วัน</div></div><div class="card kpi"><div class="label">1 ปีล่าสุด</div><div class="num">${s.orderCount} ครั้ง</div></div><div class="card kpi"><div class="label">ยอดซื้อ 1 ปี</div><div class="num money">${fmt(s.total)}</div></div><div class="card kpi"><div class="label">ยอดค้าง</div><div class="num money">${fmt(s.bal)}</div></div><div class="card kpi"><div class="label">Average Order</div><div class="num money">${fmt(s.avgOrder)}</div></div><div class="card kpi"><div class="label">ปกติจ่าย</div><div class="num">${p.payment_avg_days} วัน</div></div><div class="card kpi"><div class="label">รอบสั่ง</div><div class="num">${s.avgGap} วัน</div></div><div class="card kpi"><div class="label">คาดว่าจะสั่งอีก</div><div class="num">${s.next} วัน</div></div></div><div class="card" style="margin-top:12px"><div class="row"><button onclick="newOrder('${p.id}')">+ เปิดออเดอร์</button><button class="btn3" onclick="location.href='tel:${p.phone}'">โทร</button><button class="btn3" onclick="window.open('https://maps.google.com/?q='+encodeURIComponent('${p.address}'))">Map</button></div></div>`}
function products(){return `<div class="row mobile-stack"><div class="title" style="flex:1">Product Master</div><button onclick="newProduct()">+ Product</button></div><div class="table-wrap card"><table class="table"><thead><tr><th>SKU</th><th>สินค้า</th><th>ลัง</th><th>Retail</th><th>Restaurant</th><th>Mart</th><th>Wholesale</th><th>Stock</th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${p.sku}</td><td><b>${p.name_th}</b><div class="sub">${p.name_kr}</div></td><td>${p.box_qty} pack<br><span class="sub">${p.spec}</span></td><td>${fmt(p.prices.retail)}</td><td>${fmt(p.prices.restaurant)}</td><td>${fmt(p.prices.mart)}</td><td>${fmt(p.prices.wholesale)}</td><td>${p.stock_pack}</td></tr>`).join('')}</tbody></table></div>`}
function orders(){if(App.selectedOrder)return orderDetail(App.selectedOrder);return `<div class="row mobile-stack"><div class="title" style="flex:1">Orders</div><button onclick="newOrder()">+ เปิดออเดอร์</button></div><div class="list">${db.orders.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(o=>{const p=partner(o.partner_id);return `<div class="list-item"><div style="flex:1"><b>${o.no}</b><div class="sub">${o.date} · ${p?.name||''} · ${o.status}</div><div class="money"><b>${fmt(o.total)}</b></div></div><span class="pill ${o.payment_status==='paid'?'green':'orange'}">${o.payment_status}</span><button onclick="viewOrder('${o.id}')">เปิด</button></div>`}).join('')}</div>`}
function viewOrder(id){App.page='orders';App.selectedOrder=id;render()}
function newOrder(pid=''){const id=uid('ord');db.orders.unshift({id,no:'B2B-'+today().slice(2).replaceAll('-','')+'-'+String(db.orders.length+1).padStart(4,'0'),date:today(),partner_id:pid||db.partners[0].id,status:'open',payment_status:'unpaid',due_date:today(),paid_date:'',items:[],total:0});save();viewOrder(id)}
function orderDetail(id){const o=db.orders.find(x=>x.id===id);const p=partner(o.partner_id);return `<button class="btn3 no-print" onclick="App.selectedOrder=null;render()">← กลับ</button><div class="card"><div class="row mobile-stack"><div style="flex:1"><div class="title">${o.no}</div><div class="sub">${o.date} · ${p.name}</div></div><div class="num money">${fmt(o.total)}</div></div><div class="form-grid no-print"><div><label>Partner</label><select onchange="o.partner_id=this.value;repriceOrder(o);save();render()">${db.partners.map(x=>`<option value="${x.id}" ${x.id===o.partner_id?'selected':''}>${x.name} (${x.tier})</option>`).join('')}</select></div><div><label>สถานะเงิน</label><select onchange="o.payment_status=this.value;save();render()"><option ${o.payment_status==='unpaid'?'selected':''} value="unpaid">unpaid</option><option ${o.payment_status==='paid'?'selected':''} value="paid">paid</option></select></div></div></div><div class="card no-print" style="margin-top:12px"><div class="title">เพิ่มสินค้า</div>${addItemForm(o.id)}</div><div class="card" style="margin-top:12px"><div class="table-wrap"><table class="table"><thead><tr><th>สินค้า</th><th>หน่วย</th><th>จำนวน</th><th>แพ็กจริง</th><th>ราคา/แพ็ก</th><th>รวม</th><th class="no-print"></th></tr></thead><tbody>${o.items.map((it,idx)=>{const pr=product(it.product_id);return `<tr><td>${pr.name_th}<div class="sub">${pr.name_kr}</div></td><td>${it.sell_unit}</td><td>${it.qty}</td><td>${it.pack_qty}</td><td>${fmt(it.unit_price)}</td><td>${fmt(it.line_total)}</td><td class="no-print"><button class="btn-danger" onclick="removeItem('${o.id}',${idx})">ลบ</button></td></tr>`}).join('')}</tbody></table></div><h2 class="money">รวม ${fmt(o.total)}</h2></div><div class="card no-print" style="margin-top:12px"><div class="row mobile-stack"><button onclick="printTrade('${o.id}')">พิมพ์ 거래명세서</button><button class="btn2" onclick="openDoc('${o.id}')">เปิดเอกสาร</button><button class="btn3" onclick="exportOMS('${o.id}')">Export OMS CSV</button><button class="btn3" onclick="exportTax('${o.id}','cash')">현금영수증 CSV</button><button class="btn3" onclick="exportTax('${o.id}','tax')">세금계산서 CSV</button></div></div>`}
function addItemForm(oid){return `<div class="form-grid"><div><label>สินค้า</label><select id="add_prod">${db.products.map(p=>`<option value="${p.id}">${p.name_th}</option>`).join('')}</select></div><div><label>หน่วยขาย</label><select id="add_unit"><option value="pack">แพ็ก/ชิ้น</option><option value="box">ลัง</option></select></div><div><label>จำนวน</label><input class="input" id="add_qty" type="number" value="1" min="1"></div><div style="display:flex;align-items:end"><button onclick="addItem('${oid}')">เพิ่ม</button></div></div>`}
function addItem(oid){const o=db.orders.find(x=>x.id===oid);const pr=product(document.getElementById('add_prod').value);const sell_unit=document.getElementById('add_unit').value;const qty=Number(document.getElementById('add_qty').value||1);const p=partner(o.partner_id);const pack_qty=sell_unit==='box'?qty*pr.box_qty:qty;const unit_price=pr.prices[p.tier]||pr.prices.retail;const line_total=pack_qty*unit_price;o.items.push({product_id:pr.id,sell_unit,qty,pack_qty,unit_price,line_total});calc(o);save();render()}
function removeItem(oid,idx){const o=db.orders.find(x=>x.id===oid);o.items.splice(idx,1);calc(o);save();render()}function calc(o){o.total=o.items.reduce((a,it)=>a+it.line_total,0)}function repriceOrder(o){const p=partner(o.partner_id);for(const it of o.items){const pr=product(it.product_id);it.unit_price=pr.prices[p.tier]||pr.prices.retail;it.line_total=it.pack_qty*it.unit_price}calc(o)}
function docs(){return `<div class="title">Documents / Export</div><div class="card"><div class="sub">เลือกออเดอร์จากหน้า Orders แล้วกดปุ่มเอกสารได้เลย</div><br><div class="list">${db.orders.slice(0,8).map(o=>`<div class="list-item"><div style="flex:1"><b>${o.no}</b><div class="sub">${partner(o.partner_id).name} · ${fmt(o.total)}</div></div><button onclick="openDoc('${o.id}')">거래명세서</button><button class="btn3" onclick="exportOMS('${o.id}')">OMS</button></div>`).join('')}</div></div>`}
function openDoc(id){App.page='docview';document.body.innerHTML=top()+`<main class="app"><div class="no-print row" style="margin-bottom:10px"><button class="btn3" onclick="render()">← กลับ</button><button onclick="window.print()">Print / Save PDF</button></div>${tradeDoc(id)}</main>`}
function printTrade(id){openDoc(id);setTimeout(()=>window.print(),150)}
function tradeDoc(id){const o=db.orders.find(x=>x.id===id),p=partner(o.partner_id);const supplier={name:'메콩푸드 주식회사',ceo:'JUTATIT MONGKON',biz:'684-86-02697',phone:'010-2104-1817',addr:'경기도 화성시 배양북길 39, 나동 (배양동)'};const rows=o.items.map((it,i)=>{const pr=product(it.product_id);return `<tr><td>${i+1}</td><td>${pr.name_kr}</td><td>${pr.spec}</td><td>${it.qty}</td><td>${it.sell_unit}</td><td>${fmt(it.unit_price).replace('₩ ','')}</td><td>${fmt(it.line_total).replace('₩ ','')}</td><td></td><td></td></tr>`}).join('')+Array.from({length:8-o.items.length},(_,i)=>`<tr><td>${o.items.length+i+1}</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>`).join('');function sheet(type){return `<div class="doc-sheet"><div class="doc-title">거 래 명 세 서 <span style="font-size:14px;color:#111">(${type})</span></div><div class="doc-grid"><div>거래일자</div><div>${o.date}</div><div>페이지</div><div>1 / 1</div><div>공급받는자</div><div><b>${p.name}</b> 귀하</div><div>공급자</div><div><b>${supplier.name}</b></div><div>사업장</div><div>${p.address}</div><div>등록번호</div><div>${supplier.biz}</div><div>전화번호</div><div>${p.phone}</div><div>전화</div><div>${supplier.phone}</div><div>합계금액</div><div><b>${fmt(o.total)}</b></div><div>미수금</div><div>${fmt(partnerStats(p.id).bal)}</div></div><table class="doc-table"><thead><tr><th>번호</th><th>품목</th><th>규격</th><th>수량</th><th>단위</th><th>단가</th><th>공급가액</th><th>세액</th><th>비고</th></tr></thead><tbody>${rows}</tbody></table><div class="doc-total"><div>공급가액<br><b>${fmt(o.total)}</b></div><div>세액<br><b>부가세별도</b></div><div>합계금액<br><b>${fmt(o.total)}</b></div><div>인수자</div></div></div>`}return `<div class="doc">${sheet('공급자용')}${sheet('공급받는자용')}<div class="sub">*부가세별도</div></div>`}
function csvDownload(name,rows){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportOMS(id){const o=db.orders.find(x=>x.id===id),p=partner(o.partner_id);const rows=[['주문번호','거래일자','거래처명','전화','주소','SKU','상품명','수량','단가','금액']];o.items.forEach(it=>{const pr=product(it.product_id);rows.push([o.no,o.date,p.name,p.phone,p.address,pr.sku,pr.name_kr,it.pack_qty,it.unit_price,it.line_total])});csvDownload(o.no+'_OMS.csv',rows)}
function exportTax(id,type){const o=db.orders.find(x=>x.id===id),p=partner(o.partner_id);const rows=type==='cash'?[['거래일자','상호','전화번호','공급가액','비고'],[o.date,p.name,p.phone,o.total,o.no]]:[['작성일자','공급받는자상호','사업자번호','공급가액','세액','품목','비고'],[o.date,p.name,p.biz_no,o.total,'부가세별도',o.items.map(it=>product(it.product_id).name_kr).join(' / '),o.no]];csvDownload(o.no+'_'+(type==='cash'?'cash_receipt':'tax_invoice')+'.csv',rows)}
function newPartner(){const name=prompt('ชื่อ Partner');if(!name)return;db.partners.push({id:uid('pt'),name,tier:'restaurant',phone:'',address:'',seller:'',credit_days:7,route_day:'',payment_avg_days:0,balance:0,tax_type:'tax_invoice',biz_no:''});save();render()}
function newProduct(){alert('V2 draft: เพิ่ม/แก้ Product เต็มรูปแบบจะเปิดใน V2.1 ตอนนี้ดู Product Master และราคา Tier ได้ก่อน')}
function openSettings(){alert('V2 ใช้ LocalStorage ก่อน ถ้าจะต่อ Supabase ให้รัน supabase/schema.sql แล้วเราจะใส่ URL + anon key ใน V2.1')}
render();
